POST http://localhost:3000
Content-Type: application/json

{
    "messages": "get all users  having savings above 3500 in json"
}

### Langgraph - Test incremental of numbers with nodes and edge
POST http://localhost:3000/increment
Content-Type: application/json

{
    "number": 9
}


### Langgraph - ollama test
POST http://localhost:3000/ollama
Content-Type: application/json

{
    "query": "tell me latest weather of New York"
}



### Langgraph - ollama with langchain for latest weather upate
POST http://localhost:3000/weather
Content-Type: application/json

{
    "query": "How is Thimphu looking like?"
}

### Langgraph - ollama with langchain for latest weather upate using agent
POST http://localhost:3000/weather/agent
Content-Type: application/json

{
    
   // "query": "tell me about Indian flag"
    //"query": "who is Hitler and tell me how WWII started"
   "query": "I wanted to visit Delhi tomorrow. how is it"
}